### ISSUE TITLE
Check support for correct Python version in ms5837.py

### ISSUE THREAD

**Issue by mortenfyhn** [vortexntnu/rov-control#41]
It has some trailing 'l's on lines 183 and 184 which are not supported by Python 3.6.

On lines 4, 86, 93, and 97, it has Python 2 style print statements.

Should check which Python version is actually used by ROS, and fix the above if needed.

**Comment by sindrehan** [comment]
ROS Kinetic uses Python 2.7, so there is no need for Python 3 compatability.
See [REP3](http://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021).
