### ISSUE TITLE
Use enums for indices in controller_ros.h

### ISSUE THREAD

**Issue by mortenfyhn** [vortexntnu/rov-control#45]
I suggest replacing
```
  const uint8_t WRENCH_SURGE = 0;
  const uint8_t WRENCH_SWAY  = 1;
  const uint8_t WRENCH_HEAVE = 2;
  const uint8_t WRENCH_ROLL  = 3;
  const uint8_t WRENCH_PITCH = 4;
  const uint8_t WRENCH_YAW   = 5;

  const uint8_t POSITION_SURGE = 0;
  const uint8_t POSITION_SWAY  = 1;
  const uint8_t POSITION_HEAVE = 2;

  const uint8_t EULER_YAW   = 0;
  const uint8_t EULER_PITCH = 1;
  const uint8_t EULER_ROLL  = 2;
```
with three enum declarations inside the class.

**Comment by PeterAaser** [comment]
https://camo.githubusercontent.com/956360d829b049085b77cd8dcdb25c4e1288622f/68747470733a2f2f7261776769742e636f6d2f74616261746b696e732f62696b65736865642f6d61737465722f646f63732f69636f6e2e737667

**Comment by mortenfyhn** [comment]
![012 jpg 0x780_q85_upscale](https://user-images.githubusercontent.com/6639836/35278830-7bf41a36-004b-11e8-8a17-36af9056d0b6.jpg)
